# Generated by Django 3.2.7 on 2023-01-05 01:48

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country',
            field=django_countries.fields.CountryField(default='Taiwan', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo1',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to='', verbose_name='Photo1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo2',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to='', verbose_name='Photo2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo3',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to='', verbose_name='Photo3'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo4',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to='', verbose_name='Photo4'),
        ),
    ]
