# Generated by Django 3.2.7 on 2023-01-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cover_photo',
            field=models.ImageField(blank=True, default='../../client/sample_images/house_sample.jpg', null=True, upload_to='', verbose_name='Main Photo'),
        ),
    ]
